### ISSUE TITLE
Stream instean od loop

### ISSUE THREAD

**Issue by m00thie** [Wr-40Java/back-end-app#164]
https://github.com/Wr-40Java/back-end-app/blob/3a8816eb0e1a3a8cd8e65011033b3365cc943d98/src/main/java/Wr40/cardiary/service/InsuranceTypeService.java#L46

I would recommend to use stream here with single map instead of for loop

**Comment by tomeee121** [comment]
closed: https://github.com/Wr-40Java/back-end-app/commit/31b73c462c1ae10ebd3d32abb556c711fecdc6b0
